

export const FETCH_PENDING_EMPLOYEE_SUCCESS = 'FETCH_PENDING_EMPLOYEE_SUCCESS';
export const FETCH_WORKED_EMPLOYEE_SUCCESS = 'FETCH_WORKED_EMPLOYEE_SUCCESS';
export const FETCH_CREATE_PENDING_ENTRY = 'FETCH_CREATE_PENDING_ENTRY';
export const FETCH_GET_EMPLOYEE_NAME_WITH_CODE = 'FETCH_GET_EMPLOYEE_NAME_WITH_CODE';
export const FETCH_GET_EMPLOYEE_CODE_WITH_NAME = 'FETCH_GET_EMPLOYEE_CODE_WITH_NAME';
export const FETCH_ALL_EMPLOYEE = 'FETCH_ALL_EMPLOYEE';
export const UPDATE_PENDING_EMPLOYEE = 'UPDATE_PENDING_EMPLOYEE';
export const GET_WORKED_EMPLOYEE_WITH_DATE = 'GET_WORKED_EMPLOYEE_WITH_DATE'
export const GET_EMPLOYEE_ID_USERS = 'GET_EMPLOYEE_ID_USERS'
export const CREATE_NEW_USER = 'CREATE_NEW_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const FETCH_ERROR = 'FETCH_ERROR';
